### ISSUE TITLE
netinfo.c: Inet6Rresolve() passes the size of a source string to strncpy_s()

### ISSUE THREAD

**Issue by setharnold** [UVP-Tools/UVP-Tools#10]
I reviewed uvp-monitor/ version 288eea690ffe61f189ea51b13c77c6bb465953ec
as checked out from https://github.com/UVP-Tools/UVP-Tools.git . This
should not be considered a full security audit but rather a quick gauge of
maintainability.

- netinfo.c: Inet6Rresolve() passes the size of a source string to the
  strncpy_s() routines rather than the size of the destination buffer. It
  doesn't currently look like a security issue but it could become one.

Thanks

**Comment by UVP-Tools** [comment]
Hi, Setharnold
Thank you.

Since all inputs are known at compile time, it doesn't look like a security issue. The destination buffer size is 128 that is much more than the source string size even we make some modification. We will close this issue.
