### ISSUE TITLE
cpuinfo.c: hardcodes a maximum number of CPUs of only 64

### ISSUE THREAD

**Issue by setharnold** [UVP-Tools/UVP-Tools#11]
I reviewed uvp-monitor/ version 288eea690ffe61f189ea51b13c77c6bb465953ec
as checked out from https://github.com/UVP-Tools/UVP-Tools.git . This
should not be considered a full security audit but rather a quick gauge of
maintainability.

- cpuinfo.c: hardcodes a maximum number of CPUs of only 64! It's possible
  for end consumers to order 384 core systems.

Thanks

**Comment by UVP-Tools** [comment]
Hi, Setharnold
Thank you.

64 is our maximum number of CPUs Specifications. A VM with more than 64 CPUs configured will not be created. We will close this issue.
