### ISSUE TITLE
xenctlmon.c: condition() is useless

### ISSUE THREAD

**Issue by setharnold** [UVP-Tools/UVP-Tools#12]
I reviewed uvp-monitor/ version 288eea690ffe61f189ea51b13c77c6bb465953ec
as checked out from https://github.com/UVP-Tools/UVP-Tools.git . This
should not be considered a full security audit but rather a quick gauge of
maintainability.

- xenctlmon.c: condition() is useless

Thanks

**Comment by UVP-Tools** [comment]
Hi, Setharnold
Thank you.

The function is for unit test, let it be. :)

**Comment by UVP-Tools** [comment]
Hi, Setharnold
Thank you.

The function is for unit test, let it be. :) We will close this issue.
