### ISSUE TITLE
xenctlmon.c: do_time_sync() is brutal

### ISSUE THREAD

**Issue by setharnold** [UVP-Tools/UVP-Tools#13]
I reviewed uvp-monitor/ version 288eea690ffe61f189ea51b13c77c6bb465953ec
as checked out from https://github.com/UVP-Tools/UVP-Tools.git . This
should not be considered a full security audit but rather a quick gauge of
maintainability.

- xenctlmon.c: do_time_sync() is brutal -- it jumps the clock by entire
  seconds rather than skewing time as ntpd would

Thanks

**Comment by UVP-Tools** [comment]
Hi, Setharnold
Thank you.
 
There may be upto one secend deviation in this function. We are going to fix it by two ways:
(1)replace stime by other interface to improve precision
(2)make a reasonable compensation

**Comment by UVP-Tools** [comment]
Hi, Setharnold
Thank you.

There may be upto one second deviation in this function. We are going to fix it by two ways:
(1)replace stime by other interface to improve precision
(2)make a reasonable compensation

**Comment by UVP-Tools** [comment]
Hi, Setharnold
We have remove this function, it has no used. so we close this issue.
