### ISSUE TITLE
xenctlmon.c: do_cp_version_files()

### ISSUE THREAD

**Issue by setharnold** [UVP-Tools/UVP-Tools#14]
I reviewed uvp-monitor/ version 288eea690ffe61f189ea51b13c77c6bb465953ec
as checked out from https://github.com/UVP-Tools/UVP-Tools.git . This
should not be considered a full security audit but rather a quick gauge of
maintainability.

- xenctlmon.c: do_cp_version_files() should not rely upon
  snprintf_s() to build the command string when all inputs are known at
  compile time, C's string concatenation is better. Also, this should
  probably be re-written to use C native API. Or thrown away entirely to
  perform updates via the installed system's native updates.

Thanks

**Comment by UVP-Tools** [comment]
Hi, Setharnold
Thank you.

snprintf_s is a security function which is mandatory according to our security compliance. We will close this issue.
