### ISSUE TITLE
xenctlmon.c: do_tools_watch_proc() wakes up every five seconds

### ISSUE THREAD

**Issue by setharnold** [UVP-Tools/UVP-Tools#15]
I reviewed uvp-monitor/ version 288eea690ffe61f189ea51b13c77c6bb465953ec
as checked out from https://github.com/UVP-Tools/UVP-Tools.git . This
should not be considered a full security audit but rather a quick gauge of
maintainability.

- xenctlmon.c: do_tools_watch_proc() wakes up every five seconds to
  perform hypercalls, memory allocations, string searches, directory and
  file operations, and command executions. In every VM on a system with
  thousands of VMs?

Thanks

**Comment by UVP-Tools** [comment]
Hi, Setharnold
Thank you.

The 5 seconds is the maximum timeout value rather than a periodic time. We will close this issue.
