### ISSUE TITLE
xenctlmon.c: set_tip_message() uses snprintf_s() in order to build strings

### ISSUE THREAD

**Issue by setharnold** [UVP-Tools/UVP-Tools#16]
I reviewed uvp-monitor/ version 288eea690ffe61f189ea51b13c77c6bb465953ec
as checked out from https://github.com/UVP-Tools/UVP-Tools.git . This
should not be considered a full security audit but rather a quick gauge of
maintainability.

- xenctlmon.c: set_tip_message() uses snprintf_s() in order to build
  strings from contents that are completely known at compile time. C's
  string concatenation is better.

Thanks

**Comment by UVP-Tools** [comment]
Hi, Setharnold
Thank you.

snprintf_s is a security function which is mandatory according to our security compliance. We will close this issue.
