### ISSUE TITLE
xenstore_common.c: openxenstore() uses fcntl(.. FD_CLOEXEC);

### ISSUE THREAD

**Issue by setharnold** [UVP-Tools/UVP-Tools#17]
I reviewed uvp-monitor/ version 288eea690ffe61f189ea51b13c77c6bb465953ec
as checked out from https://github.com/UVP-Tools/UVP-Tools.git . This
should not be considered a full security audit but rather a quick gauge of
maintainability.

- xenstore_common.c: openxenstore() uses fcntl(.. FD_CLOEXEC); modern Linux
  allows setting this directly in the open(2) call.

Thanks

**Comment by UVP-Tools** [comment]
Hi, Setharnold
Thank you.

The handle is returned from the xenstore interface which is compiled as binary library. I don't think it's a good idea to add the FD_CLOEXEC option in the library.

**Comment by UVP-Tools** [comment]
Hi, Setharnold
Thank you.

The handle is returned from the xenstore interface which is compiled as binary library. We don't think it's a good idea to add the FD_CLOEXEC option in the library. We will close this issue.
