### ISSUE TITLE
void *handle parameters

### ISSUE THREAD

**Issue by setharnold** [UVP-Tools/UVP-Tools#19]
I reviewed uvp-monitor/ version 288eea690ffe61f189ea51b13c77c6bb465953ec
as checked out from https://github.com/UVP-Tools/UVP-Tools.git . This
should not be considered a full security audit but rather a quick gauge of
maintainability.

Many functions use void *handle parameters and cast the handle in every
function body. This allows type-punning bugs to thrive. Use strong types.

Thanks

**Comment by UVP-Tools** [comment]
Hi, Setharnold
Thank you.

All void *handle parameters are casted to xs_handle * type. And they are all passed from thread function at the bottom of call stack.We will close this issue.
