### ISSUE TITLE
disk.c: strAdd(), strMInux(), strMulti() are extremely complicated

### ISSUE THREAD

**Issue by setharnold** [UVP-Tools/UVP-Tools#2]
I reviewed uvp-monitor/ version 288eea690ffe61f189ea51b13c77c6bb465953ec
as checked out from https://github.com/UVP-Tools/UVP-Tools.git . This
should not be considered a full security audit but rather a quick gauge of
maintainability.

- disk.c: strAdd(), strMInux(), strMulti() are extremely complicated. Why
  aren't they strtoll(A) + or - or * strtoll(B)? They could be ~ten lines
  long with much simpler error handling.

Thanks

**Comment by UVP-Tools** [comment]
Hi, Setharnold
Thank you.

The operation interfaces with string have better transportability over 32-bit and 64-bit cpu. They are fully tested and don't need any modification.

**Comment by UVP-Tools** [comment]
Hi, Setharnold
Thank you.

The operation interfaces with string have better transportability over 32-bit and 64-bit cpu. They are fully tested and don't need any modification. We will close this issue.
