### ISSUE TITLE
if (NULL == foo) return false;

### ISSUE THREAD

**Issue by setharnold** [UVP-Tools/UVP-Tools#20]
I reviewed uvp-monitor/ version 288eea690ffe61f189ea51b13c77c6bb465953ec
as checked out from https://github.com/UVP-Tools/UVP-Tools.git . This
should not be considered a full security audit but rather a quick gauge of
maintainability.

Many functions use "if (NULL == foo) return false;" kinds of guards.
Should these instead issue asserts() so that error condtions can be
discovered and repaied?

Thanks

**Comment by UVP-Tools** [comment]
Hi, Setharnold
Thank you.

The no-null check is effective in both debug and release version. We will close this issue.
