### ISSUE TITLE
cppcheck results

### ISSUE THREAD

**Issue by setharnold** [UVP-Tools/UVP-Tools#21]
Hello, the following is a list of issues reported by the cppcheck static analysis tool. Perhaps not all issues are bugs but it may still be worth addressing everything it reports to make it easier to integrate cppcheck into the development process of UVP-Tools.

Thanks

[uvp-monitor/check_kernel.c:205]: (error) Resource leak: filp
[uvp-monitor/network.c:1248]: (error) Address of local auto-variable assigned to a function parameter.
[uvp-monitor/securec/src/input.inl:545]: (error) va_list 'arglistsave' used before va_start() was called.
[uvp-monitor/securec/src/input.inl:717]: (error) va_list 'arglistsave' used before va_start() was called.
[uvp-monitor/securec/src/input.inl:782]: (error) va_list 'arglistsave' used before va_start() was called.
[uvp-monitor/securec/src/input.inl:784]: (error) va_list 'arglistsave' used before va_start() was called.
[uvp-monitor/securec/src/input.inl:793]: (error) va_list 'arglistsave' used before va_start() was called.
[uvp-monitor/securec/src/input.inl:1990]: (error) va_list 'arglistsave' used before va_start() was called.
[uvp-monitor/securec/src/input.inl:2077]: (error) va_list 'arglistsave' used before va_start() was called.
[uvp-monitor/securec/src/input.inl:715]: (error) va_list 'arglistsave' used before va_start() was called.
[uvp-monitor/securec/src/input.inl:778]: (error) va_list 'arglistsave' used before va_start() was called.
[uvp-monitor/securec/src/input.inl:779]: (error) va_list 'arglistsave' used before va_start() was called.
[uvp-monitor/securec/src/input.inl:791]: (error) va_list 'arglistsave' used before va_start() was called.
[uvp-monitor/securec/src/input.inl:1986]: (error) va_list 'arglistsave' used before va_start() was called.
[uvp-monitor/securec/src/input.inl:1988]: (error) va_list 'arglistsave' used before va_start() was called.
[uvp-xenpv/others/FEDORA12/xen-platform-pci/xenbus_probe.c:1276]: (error) Possible null pointer dereference: drv
[uvp-xenpv/others/FEDORA9/xen-platform-pci/xenbus_probe.c:1186]: (error) Possible null pointer dereference: drv
[uvp-xenpv/others/RHEL4/xen-platform-pci/xenbus_probe.c:1069]: (error) Possible null pointer dereference: drv
[uvp-xenpv/others/RHEL4/xen-platform-pci/xenbus_probe.c:250]: (error) Uninitialized variable: bus
[uvp-xenpv/others/RHEL5/xen-platform-pci/xenbus_probe.c:1077]: (error) Possible null pointer dereference: drv
[uvp-xenpv/others/SLES10/xen-platform-pci/xenbus_probe.c:1075]: (error) Possible null pointer dereference: drv
[uvp-xenpv/others/SLES10/xen-vbd/blkfront.c:1103]: (error) Uninitialized variable: pfn
[uvp-xenpv/others/Ubuntu10/xen-platform-pci/xenbus_probe.c:1280]: (error) Possible null pointer dereference: drv
[uvp-xenpv/others/Ubuntu8/xen-platform-pci/xenbus_probe.c:1186]: (error) Possible null pointer dereference: drv
[uvp-xenpv/uvp-classic_xen_driver-2.6.32to3.0.x/xen-platform-pci/2.6.27/xenbus_probe.c:1124]: (error) Possible null pointer dereference: drv
[uvp-xenpv/uvp-classic_xen_driver-2.6.32to3.0.x/xen-platform-pci/2.6.32/xenbus_probe.c:1407]: (error) Possible null pointer dereference: drv
[uvp-xenpv/uvp-classic_xen_driver-2.6.32to3.0.x/xen-platform-pci/3.0.13/xenbus_probe.c:1465]: (error) Possible null pointer dereference: drv
[uvp-xenpv/uvp-classic_xen_driver-2.6.32to3.0.x/xen-platform-pci/3.0.76/xenbus_probe.c:1451]: (error) Possible null pointer dereference: drv

**Comment by UVP-Tools** [comment]
Hi, Setharnold
Thank you.

The error logs “va_list 'arglistsave' used before va_start() was called.” does not need to modify, reason as blow: 
The parameter arglist of securec_input_s is passed through the scanf_s series of functions, the va_start has been called before it was passed, and the local variables arglistsave only used to preserve the state of the arglist variable, which was assigned by va_copy, can not call va_start.

We will complete to fix the others errors next week, includes:
A) Uninitialized variable.
B) Address of local auto-variable assigned to a function parameter.
C) Resource leak.
D) Possible null pointer dereference: drv.

**Comment by UVP-Tools** [comment]
Hi, Setharnold
I've fixed the issue, The fixed version: 2.2.0.313.
Download link: https://github.com/UVP-Tools/UVP-Tools/releases/tag/2.2.0.313
So I will close this issue.

Thank you.
