### ISSUE TITLE
disk.c: freePath() performs redundant non-NULL checks

### ISSUE THREAD

**Issue by setharnold** [UVP-Tools/UVP-Tools#5]
I reviewed uvp-monitor/ version 288eea690ffe61f189ea51b13c77c6bb465953ec
as checked out from https://github.com/UVP-Tools/UVP-Tools.git . This
should not be considered a full security audit but rather a quick gauge of
maintainability.

- disk.c: freePath() performs redundant non-NULL checks; free(NULL) is
  specified to take no action. freePath() could be three lines long, or
  even removed entirely, since it is used four times, once incorrectly.

**Comment by UVP-Tools** [comment]
Hi, Setharnold
Thank you.

free(NULL) is safe in most cases. It should be safer keeping the non-NULL check than depending on the interface implementation. We will close this issue.
