### ISSUE TITLE
disk.c: isCorrectDev() skips SAS drives?

### ISSUE THREAD

**Issue by setharnold** [UVP-Tools/UVP-Tools#6]
I reviewed uvp-monitor/ version 288eea690ffe61f189ea51b13c77c6bb465953ec
as checked out from https://github.com/UVP-Tools/UVP-Tools.git . This
should not be considered a full security audit but rather a quick gauge of
maintainability.

- disk.c: isCorrectDev() skips SAS drives?

Thanks

**Comment by UVP-Tools** [comment]
Hi, Setharnold
Thank you.

SAS device will be processed in this function. We will close this issue.
