### ISSUE TITLE
netinfo.c: GetIpv6Flux() calls getVifData() repeatedly

### ISSUE THREAD

**Issue by setharnold** [UVP-Tools/UVP-Tools#8]
I reviewed uvp-monitor/ version 288eea690ffe61f189ea51b13c77c6bb465953ec
as checked out from https://github.com/UVP-Tools/UVP-Tools.git . This
should not be considered a full security audit but rather a quick gauge of
maintainability.

- netinfo.c: GetIpv6Flux() calls getVifData() repeatedly which re-walks
  the same string over and over again. This seems appropriate for
  sscanf(3) instead, to capture all values once using a standard C library
  function?

Thanks

**Comment by UVP-Tools** [comment]
Hi, Setharnold
Thank you.

getVifData is robust and maintainable when the format of source string is changed. We will close this issue.
