### ISSUE TITLE
netinfo.c: GetIpv4VifGateway() has shell command line injection flaw

### ISSUE THREAD

**Issue by setharnold** [UVP-Tools/UVP-Tools#9]
I reviewed uvp-monitor/ version 288eea690ffe61f189ea51b13c77c6bb465953ec
as checked out from https://github.com/UVP-Tools/UVP-Tools.git . This
should not be considered a full security audit but rather a quick gauge of
maintainability.

- netinfo.c: GetIpv4VifGateway() has shell command line injection flaw via
  ifname parameter

Thanks

**Comment by UVP-Tools** [comment]
Hi, Setharnold
      There is indeed command line injection risk. We plan to fix it through checking special characters including but not limited back-slant, slash, semicolon, quotation marks.

**Comment by UVP-Tools** [comment]
Hi, Setharnold
Thank you.

There is indeed command line injection risk. We plan to fix it through checking special characters including but not limited back-slant, slash, semicolon, quotation marks.

**Comment by UVP-Tools** [comment]
Hi, Setharnold
We have fix it, and close this issue.
